#!/bin/sh
# Davyn one-shot init (run once by the s6 `init-davyn` oneshot, before the php-fpm
# and caddy longruns start). It prepares the persisted directories, applies DB
# migrations, and generates Caddy's conditional-HTTPS server stubs. It must NOT
# start any long-running process — s6 supervises php-fpm and caddy separately.
#
# `set -u` only (no `-e`): a single failed step must not abort init and leave the
# container unstartable; failures are handled/logged inline. Always exits 0.
set -u

DB_PATH="${DB_PATH:-/var/lib/davyn/davyn.sqlite}"
DATA_DIR="$(dirname "$DB_PATH")"
CERT_DIR="${CERT_DIR:-/config/certs}"
CERT_FILE="${CERT_FILE:-davyn.crt}"
KEY_FILE="${KEY_FILE:-davyn.key}"
HTTPS_PORT="${HTTPS_PORT:-8443}"

# Full cert/key paths (the container env carries CERT_FILE/KEY_FILE as basenames so
# PHP's Config sees basenames; here we need absolute paths for Caddy).
CERT="$CERT_DIR/$CERT_FILE"
KEY="$CERT_DIR/$KEY_FILE"

# ── Persisted directories ───────────────────────────────────────────────────
# Database / backups / imports / exports live under the data volume.
mkdir -p "$DATA_DIR"
chown -R www-data:www-data "$DATA_DIR"
chmod 750 "$DATA_DIR"

# Certificate store (written by the app as www-data, read by Caddy in this image).
mkdir -p "$CERT_DIR/backups"
chown -R www-data:www-data "$CERT_DIR"
chmod 755 "$(dirname "$CERT_DIR")" 2>/dev/null || true
chmod 750 "$CERT_DIR" "$CERT_DIR/backups"

# ── Database migrations (idempotent; non-fatal) ─────────────────────────────
# Run as www-data so the SQLite file stays owned by the PHP runtime.
if ! su -m -s /bin/sh -c "php /var/www/html/bin/migrate.php" www-data; then
	echo "[davyn] WARNING: database migration failed; check logs. Starting anyway." >&2
fi

# ── Caddy conditional-HTTPS stubs ───────────────────────────────────────────
# Decides — purely from files present in the cert dir — what the two listeners do:
#   * HTTPS (:8443) is served only when a valid cert/key pair exists.
#   * HTTP  (:8080) serves the app by default, OR redirects to HTTPS when the admin
#     forced HTTPS (a ".http-disabled" marker) AND a working HTTPS is available.
# The cert/HTTPS guard is a fail-safe: with no working HTTPS, plain HTTP always
# serves, so a missing/broken cert can never lock the site out.
CONF_D="/etc/caddy/conf.d"
HTTP_STUB="${CONF_D}/http.caddy"
HTTPS_STUB="${CONF_D}/https.caddy"
HTTP_DISABLED="$(dirname "$CERT")/.http-disabled"

mkdir -p "$CONF_D"

write_https_disabled() {
	printf '# Internal HTTPS disabled: no valid certificate present.\n' > "$HTTPS_STUB"
}

write_http_normal() {
	cat > "$HTTP_STUB" <<-EOF
		# HTTP listener — serving the app on :8080.
		:8080 {
			import davyn_app
		}
	EOF
}

write_http_redirect() {
	cat > "$HTTP_STUB" <<-EOF
		# Generated by davyn-init.sh — admin forced HTTPS; redirecting all HTTP to HTTPS.
		:8080 {
			redir https://{http.request.host}:${HTTPS_PORT}{http.request.uri} 308
		}
	EOF
}

# Start from a safe default: HTTP serves the app.
write_http_normal

https_ok=0
if [ -s "$CERT" ] && [ -s "$KEY" ]; then
	cat > "$HTTPS_STUB" <<EOF
# Generated by davyn-init.sh — do not edit by hand.
:${HTTPS_PORT} {
	import davyn_app
	tls ${CERT} ${KEY}
}
EOF
	echo "[davyn-caddy] certificate found; enabling internal HTTPS on :${HTTPS_PORT}"

	# Validate the assembled config. If the HTTPS block is invalid (corrupt cert,
	# unreadable key), fall back to HTTP-only rather than letting Caddy refuse to start.
	if caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/tmp/caddy-validate.log 2>&1; then
		https_ok=1
	else
		echo "[davyn-caddy] WARNING: configuration invalid with the HTTPS block; serving HTTP only."
		cat /tmp/caddy-validate.log || true
		write_https_disabled
	fi
else
	echo "[davyn-caddy] no valid certificate at ${CERT}; serving HTTP only on :8080."
	write_https_disabled
fi

# Force-HTTPS: redirect :8080 -> HTTPS only when the admin asked for it AND HTTPS is
# actually being served. Otherwise plain HTTP keeps serving (fail-safe — never lock out).
if [ -e "$HTTP_DISABLED" ]; then
	if [ "$https_ok" = "1" ]; then
		write_http_redirect
		if caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/tmp/caddy-validate.log 2>&1; then
			echo "[davyn-caddy] plain HTTP disabled; redirecting :8080 -> HTTPS."
		else
			echo "[davyn-caddy] WARNING: HTTP redirect block invalid; keeping plain HTTP."
			write_http_normal
		fi
	else
		echo "[davyn-caddy] .http-disabled present but HTTPS is not active; keeping plain HTTP (fail-safe)."
	fi
fi

exit 0
